-- FINAL CLOSING DATA: APRIL 15, 2026
-- ANCHOR: JPM @ $305.89 | LATAM: ITUB @ $9.40
CREATE TABLE Stargate_Market_Truth AS
SELECT 'JPM' AS TICKER, 305.89 AS PRICE, 'FORTRESS' AS ROLE FROM DUAL UNION ALL
SELECT 'ITUB', 9.40, 'GROWTH' FROM DUAL UNION ALL
SELECT 'MS', 191.61, 'ALPHA' FROM DUAL;
