-- JPM/C6 SYNERGY & ITAU ALPHA RECOVERY
CREATE TABLE Stargate_Big_Winners AS
SELECT 
    CASE 
        WHEN REGION = 'US' AND MOD(CLIENT_ID, 2) = 0 THEN 'JPMORGAN / C6 SYNERGY'
        WHEN REGION = 'LATAM' THEN 'ITAU UNIBANCO (ITUB)'
        ELSE 'OTHER NODES'
    END AS BIG_WINNER_ENTITY,
    AUM_USD * 0.1490 AS ALPHA_GAIN
FROM Stargate_Client_Liquidity;
