-- STARGATE V15.5: INSTITUTIONAL TELEMETRY CLASH
-- MARKET_CAP_DELTA: JPM VS SECTOR
CREATE TABLE Stargate_Institutional_Winners AS
SELECT 
    CASE 
        WHEN REGION = 'LATAM' THEN 'ITAU (MOMENTUM CHAMPION)'
        WHEN REGION = 'US' AND MOD(CLIENT_ID, 4) = 0 THEN 'MORGAN STANLEY (ATH PEAK)'
        WHEN REGION = 'US' AND MOD(CLIENT_ID, 4) = 1 THEN 'BNY MELLON (ASSET CUSTODY)'
        WHEN REGION = 'US' AND MOD(CLIENT_ID, 4) = 2 THEN 'BAC / JPM (YIELD STABILITY)'
        ELSE 'C6 BANK / DIGITAL DISRUPTION'
    END AS INSTITUTIONAL_NODE,
    AUM_USD,
    CASE 
        WHEN REGION = 'LATAM' THEN AUM_USD * 0.4400 
        WHEN MOD(CLIENT_ID, 4) = 0 THEN AUM_USD * 0.0469 
        ELSE AUM_USD * 0.1148 
    END AS ALPHA_GAIN
FROM Stargate_Client_Liquidity;
